version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: chor_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: chor_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
