# Configuración de Build
[build]
  # Directorio base para el build. Netlify ejecutará el comando desde aquí.
  base = "frontend"
  # Comando para construir el frontend (se ejecuta dentro de la base).
  command = "npm run build"
  # Directorio que se publicará (relativo a la base).
  publish = "build"
  # Directorio de las funciones (relativo a la raíz del proyecto).
  functions = "netlify/functions"

# Regla de proxy para las funciones. Todas las llamadas a /api/* irán a /.netlify/functions/*
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Regla para que el enrutamiento de React (SPA) funcione correctamente.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200