# Configuraci칩n de Build
[build]
  # Directorio donde se encuentran las funciones serverless
  functions = "netlify/functions"
  # Directorio que se publicar치 (el resultado del build de React)
  publish = "frontend/build"
  # Comando para construir el frontend
  command = "npm run build --prefix frontend"

# Reglas de redirecci칩n para una Single Page App (SPA) como React
[[redirects]]
  # Redirige todas las llamadas a /.netlify/functions a la funci칩n correspondiente
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # Redirige cualquier otra ruta al index.html para que React Router funcione
  from = "/*"
  to = "/index.html"
  status = 200
